### ISSUE TITLE
(Deb) Create symlink in /usr/local/bin

### ISSUE THREAD

**Issue by lukastrkan** [qmfrederik/dotnet-packaging#101]
Hello, 
is there a way to automaticly create symlink from install location to /usr/local/bin in deb package?

I did check #31 , but its quite old, you know.

Thanks

**Comment by qmfrederik** [comment]
The approach from #31 should still work. That approach consists of:

1. Creating a shell script which will end up in /usr/local/bin and invokes your program. You should place this file inside your C# project directory, and it should have contents like this:
```
#!/bin/sh
exec /usr/share/myprog/myprog
```

2. Update your `.csproj` file so that this file is deployed to `/usr/local/bin`:

```
<Content Include="myprog.sh" CopyToPublishDirectory="PreserveNewest" LinuxFileMode="755">
    <LinuxPath>/usr/local/bin/myprog</LinuxPath>
</Content>
```

Can you give that a try and let me know whether it works?
