### ISSUE TITLE
Why are so many DLLs in the package?

### ISSUE THREAD

**Issue by aggsol** [qmfrederik/dotnet-packaging#116]
Even a small console application is 30MB. Inside are a lot of DLL that are part of the runtime. Is the runtime not a dependency, why also provide those DLLs? Also there is Visual basic DLL and I don't even use that. How can I strip it?

**Comment by qmfrederik** [comment]
The DLLs which are packaged are the result of publishing your application as a framework-independent package using `dotnet publish`. It includes the runtime.

You are right that it may be easier to declare the runtime as a dependency. This would reduce the size of the application.

There's no built-in support for that right now, but it's something worth considering.

One caveat here would be that your users would be required to add the .NET Core repository for your operating system to their list of repositories before they can install your app, since .NET Core is not packaged by any of the major distro's (that I know of).

**Comment by aggsol** [comment]
Ok. That explains the large packages.
