### ISSUE TITLE
What it the current status of `deb` packages support?

### ISSUE THREAD

**Issue by kekekeks** [qmfrederik/dotnet-packaging#15]
As I can see there is a [feature branch](https://github.com/qmfrederik/dotnet-packaging/tree/features/deb) for that, but it has been stalled for quite a while.

I need that feature and want to help with finishing it. What is currently missing and needs to be implemented? If I remember correctly, `deb` package is a combination of `ar` and `tar.gz` archives with text-based metadata files inside, so it shouldn't be as hard as RPM.

Note: I hereby confirm that I've read https://www.debian.org/doc/manuals/maint-guide/ and have packaged several Mono-based applications. I also was a maintainer of [Mono packages for Maemo 5](https://www.youtube.com/watch?v=873Ig7-wS9Q) (Debian-based OS on Nokia N900), so I know what all those fields in control files mean.

**Comment by qmfrederik** [comment]
@kekekeks Thanks for your contributions & willing to help out.

You are right, work on the deb support has stalled for a while - mainly due to a lack of time.

I'm happy to take contributions. Yes, deb packages are a combination of `ar` + `tar.gz` archives and the maintainers guide contains a lot of valueable information on that file format (so in a sense I expect the deb format to be easier than the RPM format, for example).

Pull requests are welcome! Ideally, you send them to the feature branch and we merge the feature branch once we feel it is stable.

For me, the exit criteria is that the `dotnet deb` command can package the [demo project](https://github.com/qmfrederik/dotnet-packaging/tree/master/demo) and deploy it on a vanilla Debian/Ubuntu installation as a self-contained application.

That would include declaring dependencies, deploying it as a systemd service, creating a user + group, setting permissions,... .

**Comment by qmfrederik** [comment]
One more note - for the RPM support,  I took an some existing RPM packages (such as libplist or usbmuxd, basically because they are really straightforward) and added unit tests that re-create these packages from scratch using the code in this repository. I then tried to make the output binary compatible and added that as unit tests.

I know requiring the output to be binary compatible may seem overkill, but that way you are sure you've caught all of the subtleties of the file format.
