### ISSUE TITLE
Create symbolic link deb package

### ISSUE THREAD

**Issue by franklupo** [qmfrederik/dotnet-packaging#31]
Hi,
great work.
How to make symbolic link from /usr/share/**myprog** to /usr/bin/**myprog**?

Best regards

**Comment by qmfrederik** [comment]
One way to enable this could be to expose MSBuild properties which allow you to add additional contents to the pre/post installation scripts.

@kekekeks What do you think?

**Comment by kekekeks** [comment]
In case of `deb`-packages symlinks can be placed directly into `data.tar.xz`. `deb` packages are designed to handle everything that `make install DESTDIR=debian/{packagename}` can possibly create in that directory (that's the main way of populating package contents, actually).

I have not idea what to do with RPM.

**Comment by kekekeks** [comment]
BTW, @franklupo I'm not sure that it will even work with .NET Core, since binary might try to look for `myprog.dll` in `/usr/bin` instead of `/usr/share/myprog`, which will fail. And the common way of adding your program to `/usr/bin` with Mono was to create a shell script there. So I'd suggest to add
```
#!/bin/sh
exec /usr/share/myprog/myprog
```
and place it to `/usr/bin/myprog` using `LinuxPath`, see [example](https://github.com/qmfrederik/dotnet-packaging/blob/master/demo/demo.csproj#L15) here

**Comment by franklupo** [comment]
Possible use PostInstallScripte?

**Comment by qmfrederik** [comment]
@franklupo I think that @kekekeks 's suggestion to use a shell script and place it in `/usr/bin/myprog` using `LinuxPath` is actually the best way to implement this.

Can you give that a try and let us know if that works?

**Comment by franklupo** [comment]
@qmfrederik  Yes work. But i have new problem see issues #35

**Comment by qmfrederik** [comment]
@franklupo Just wanted to check: with all the fixes that just went in, did you manage to create a `.deb` package for your project that is installable?

**Comment by franklupo** [comment]
Ok, the problem is to keep permissions execution on the file.

>     <Content Include="myprog.sh" CopyToPublishDirectory="PreserveNewest">
>         <LinuxPath>/usr/sbin/myprog</LinuxPath>
>     </Content>

**Comment by qmfrederik** [comment]
I'd need to double check but I believe we determine whether a file is executable or not in the ArchiveBuilder:

https://github.com/qmfrederik/dotnet-packaging/blob/883187b3848267c6eb83533b566b017761a3b235/Packaging.Targets/ArchiveBuilder.cs#L280-L281

We should be able to modify that code so that it either:
- Checks for the `sh` extension and sets the file to executable if that extension is found
- Allows you to set a  `LinuxPermissions` attribute on the `Content` item in the `proj` file and allow you to override the permissions that way.

**Comment by kekekeks** [comment]
>Checks for the sh extension and sets the file to executable if that extension is found

I think we need to check for `#!` signature (e. g. `#!/bin/sh`) in files. Linux loader uses that to determine if file needs an interpreter, so we should do the same.

Overriding permissions manually would also be useful for settings stuff like suid-bit (we should NOT allow to set it for .NET Core binaries, since it **will cause major security issues**).
